# Use postgres/example user/password credentials
version: '3.1'
services:
  db:
    image: postgres
    restart: always
    ports: 
      - 8000:5432
    environment:
      POSTGRES_PASSWORD: heippi
      POSTGRES_USER: heippi
      POSTGRES_DB: heippi
